version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # rabbitmq with management interface enabled
    ports:
    - 5672:5672     # MessageBroker
    - 15672:15672   # Managing interface 
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 10

  task-producer:
    build: 
      context: .
      dockerfile: Task.Producer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  task-consumer:
    build: 
      context: .
      dockerfile: Task.Consumer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  log-consumer:
    build: 
      context: .
      dockerfile: Log.Consumer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy