version: '3.8'

services:
  db:
    image: postgres
    ports: 
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password     # Required, sets password for superuser
      - POSTGRES_USER=user             # Optional, username for default superuser (default: postgress)
      - POSTGRES_DB=library            # Optional, names database (default: {POSTGRES_USER})

  web:
    build: .
    ports: 
    - 8080:8080
    depends_on: 
      db:
        condition: 
          service_started
    restart: always
