version: '3.4'

services:
  db:
    image: mysql
    ports: 
    - 3056:3056
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  web:
    build: .
    ports: 
    - 8080:8080
    depends_on: 
      db:
        condition: 
          service_started
    restart: always
